import {useThemedStyles} from '../../../../../shared/theme';
import type {AppTheme, Scale} from '../../../../../shared/theme/theme';

const createStyles = (theme: AppTheme, scale: Scale) => ({
  overlay: {flex: 1, justifyContent: 'flex-end' as const},
  backdrop: {position: 'absolute' as const, top: 0, right: 0, bottom: 0, left: 0, backgroundColor: theme.colors.scrim},
  sheet: {maxHeight: '92%' as const, backgroundColor: theme.colors.surface, borderTopLeftRadius: scale(20),
    borderTopRightRadius: scale(20), paddingTop: scale(8), paddingHorizontal: scale(20), gap: scale(12)},
  handle: {alignSelf: 'center' as const, width: scale(40), height: scale(5), borderRadius: scale(3),
    backgroundColor: theme.colors.border},
  title: {color: theme.colors.text, fontSize: scale(22), lineHeight: scale(28), fontWeight: '700' as const,
    marginTop: scale(4)},
  content: {gap: scale(12), paddingBottom: scale(4)},
  input: {minHeight: scale(54), paddingHorizontal: scale(14), borderRadius: scale(12), borderWidth: scale(1),
    borderColor: theme.colors.border, backgroundColor: theme.colors.surfaceAlt, color: theme.colors.text,
    fontSize: scale(17)},
  note: {color: theme.colors.textMuted, fontSize: scale(14), lineHeight: scale(19)},
  label: {color: theme.colors.textMuted, fontSize: scale(15), fontWeight: '600' as const},
  npk: {gap: scale(6)},
  npkRow: {flexDirection: 'row' as const, gap: scale(8)},
  npkCell: {flex: 1, flexDirection: 'row' as const, alignItems: 'center' as const, gap: scale(6)},
  npkLetter: {color: theme.colors.text, fontSize: scale(17), fontWeight: '700' as const},
  npkInput: {flex: 1, textAlign: 'center' as const},
  amountRow: {flexDirection: 'row' as const, alignItems: 'center' as const, flexWrap: 'wrap' as const, gap: scale(8)},
  quantity: {flexGrow: 1, flexBasis: scale(110)},
  units: {flexDirection: 'row' as const, gap: scale(6)},
  priceField: {minHeight: scale(54), borderRadius: scale(12), borderWidth: scale(1), borderColor: theme.colors.border,
    backgroundColor: theme.colors.surfaceAlt, flexDirection: 'row' as const, alignItems: 'center' as const,
    paddingHorizontal: scale(14), gap: scale(8)},
  priceInput: {flex: 1, color: theme.colors.text, fontSize: scale(17), paddingVertical: scale(8)},
  suffix: {color: theme.colors.textMuted, fontSize: scale(16), fontWeight: '600' as const},
  calcLine: {borderRadius: scale(12), paddingVertical: scale(10), paddingHorizontal: scale(14),
    backgroundColor: theme.colors.accentSoft},
  calcText: {color: theme.colors.accentInk, fontSize: scale(16), fontWeight: '700' as const},
  error: {color: theme.colors.danger, fontSize: scale(15), lineHeight: scale(20)},
  buttons: {flexDirection: 'row' as const, gap: scale(12)},
  button: {flex: 1},
  delete: {minHeight: scale(44), alignItems: 'center' as const, justifyContent: 'center' as const},
  deleteText: {color: theme.colors.danger, fontSize: scale(17), fontWeight: '600' as const},
  keyboardBar: {flexDirection: 'row' as const, justifyContent: 'flex-end' as const, paddingHorizontal: scale(12),
    backgroundColor: theme.colors.surface, borderTopWidth: scale(1), borderTopColor: theme.colors.border},
  keyboardDone: {minHeight: scale(44), paddingHorizontal: scale(8), justifyContent: 'center' as const},
  keyboardDoneText: {color: theme.colors.primary, fontSize: scale(17), fontWeight: '600' as const},
});

export const useStyles = () => useThemedStyles(createStyles);
