import {useThemedStyles} from '../../../shared/theme';
import type {AppTheme, Scale} from '../../../shared/theme/theme';

const createStyles = (theme: AppTheme, scale: Scale) => ({
  safe: {flex: 1, backgroundColor: theme.colors.background},
  header: {paddingHorizontal: scale(20), paddingBottom: scale(12), gap: scale(12), backgroundColor: theme.colors.background},
  content: {paddingHorizontal: scale(20), paddingTop: scale(4), paddingBottom: scale(32), gap: scale(20)},
  progress: {flexDirection: 'row' as const, gap: scale(6)},
  progressBar: {flex: 1, height: scale(6), borderRadius: scale(999), backgroundColor: theme.colors.border},
  progressDone: {backgroundColor: theme.colors.primary},
  title: {color: theme.colors.text, fontSize: scale(28), lineHeight: scale(34), fontWeight: '700' as const},
  tile: {minHeight: scale(96), borderRadius: scale(20), borderWidth: scale(2), borderColor: theme.colors.border,
    backgroundColor: theme.colors.surface, padding: scale(16), justifyContent: 'center' as const, gap: scale(4)},
  tileSelected: {borderColor: theme.colors.primary},
  tileName: {color: theme.colors.text, fontSize: scale(22), lineHeight: scale(28), fontWeight: '600' as const},
  tileDetail: {color: theme.colors.textMuted, fontSize: scale(15), lineHeight: scale(20)},
  grid: {flexDirection: 'row' as const, flexWrap: 'wrap' as const, gap: scale(12)},
  workTile: {flexBasis: '46%' as const, flexGrow: 1, minHeight: scale(96), borderRadius: scale(20), borderWidth: scale(2),
    borderColor: theme.colors.border, backgroundColor: theme.colors.surface,
    alignItems: 'center' as const, justifyContent: 'center' as const, gap: scale(8), padding: scale(10)},
  workLabel: {color: theme.colors.text, fontSize: scale(17), fontWeight: '600' as const, textAlign: 'center' as const},
  pills: {flexDirection: 'row' as const, flexWrap: 'wrap' as const, gap: scale(8)},
  pill: {borderRadius: scale(999), paddingHorizontal: scale(12), paddingVertical: scale(6), backgroundColor: theme.colors.primarySoft},
  pillText: {color: theme.colors.primary, fontSize: scale(15), fontWeight: '600' as const},
  section: {gap: scale(10)},
  label: {color: theme.colors.text, fontSize: scale(17), fontWeight: '600' as const},
  chips: {flexDirection: 'row' as const, flexWrap: 'wrap' as const, gap: scale(8)},
  segmented: {flexDirection: 'row' as const, borderRadius: scale(12), padding: scale(3), backgroundColor: theme.colors.segment},
  segment: {flex: 1, minHeight: scale(44), borderRadius: scale(10), alignItems: 'center' as const, justifyContent: 'center' as const},
  segmentSelected: {backgroundColor: theme.colors.surface, shadowColor: '#000000', shadowOpacity: 0.12,
    shadowRadius: scale(3), shadowOffset: {width: scale(0), height: scale(1)}, elevation: scale(1)},
  segmentText: {color: theme.colors.text, fontSize: scale(17), fontWeight: '600' as const},
  numberField: {minHeight: scale(64), borderRadius: scale(12), borderWidth: scale(1), borderColor: theme.colors.border,
    backgroundColor: theme.colors.surface, flexDirection: 'row' as const, alignItems: 'center' as const,
    paddingHorizontal: scale(16), gap: scale(8)},
  numberInput: {flex: 1, color: theme.colors.text, fontSize: scale(28), fontWeight: '700' as const, paddingVertical: scale(8)},
  suffix: {color: theme.colors.textMuted, fontSize: scale(20), fontWeight: '600' as const},
  input: {minHeight: scale(56), paddingHorizontal: scale(16), borderRadius: scale(12), borderWidth: scale(1),
    borderColor: theme.colors.border, backgroundColor: theme.colors.surface, color: theme.colors.text, fontSize: scale(19)},
  noteInput: {minHeight: scale(88), paddingTop: scale(14), textAlignVertical: 'top' as const},
  calcLine: {borderRadius: scale(12), paddingVertical: scale(12), paddingHorizontal: scale(16), backgroundColor: theme.colors.accentSoft},
  calcText: {color: theme.colors.accentInk, fontSize: scale(17), fontWeight: '700' as const},
  note: {color: theme.colors.textMuted, fontSize: scale(15), lineHeight: scale(20)},
  error: {color: theme.colors.danger, fontSize: scale(15), lineHeight: scale(20)},
  detailsToggle: {minHeight: scale(44), flexDirection: 'row' as const, alignItems: 'center' as const,
    justifyContent: 'space-between' as const},
  keyboardBar: {flexDirection: 'row' as const, justifyContent: 'flex-end' as const, paddingHorizontal: scale(12),
    backgroundColor: theme.colors.surface, borderTopWidth: scale(1), borderTopColor: theme.colors.border},
  keyboardDone: {minHeight: scale(44), paddingHorizontal: scale(8), justifyContent: 'center' as const},
  keyboardDoneText: {color: theme.colors.primary, fontSize: scale(17), fontWeight: '600' as const},
});

export const useStyles = () => useThemedStyles(createStyles);
